#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Twist
import sys
def turtle_circle(radius):
	rospy.init_node('turtlesim', anonymous=True)
	pub = rospy.Publisher('/turtle1/cmd_vel',
						Twist, queue_size=10)
	rate = rospy.Rate(10)
	vel = Twist()
	rospy.loginfo("Radius = %f", radius)
	pub.publish(vel)
	rate.sleep()
if __name__ == '__main__':
	try:
		turtle_circle(float(3))
	except rospy.ROSInterruptException:
		pass
